name: schoosch
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  get: ^4.7.2
  isoweek: ^1.1.3
  google_sign_in: ^7.1.1
  flutter_rating_bar: ^4.0.0
  drag_and_drop_lists: ^0.4.1
  chips_choice: ^3.0.1
  dropdown_search: ^6.0.0
  flutter_native_splash: ^2.0.1+1
  # directed_graph: ^0.4.0
  flex_color_scheme: ^8.0.0
  flutter_linkify: ^6.0.0
  url_launcher: ^6.1.5
  google_nav_bar: ^5.0.6
  dio: ^5.2.1+1
  datetime_picker_formfield_new: ^2.0.0
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.8
  pdf: ^3.8.4
  printing: ^5.9.3
  firebase_ui_auth: ^3.0.0
  firebase_ui_localizations: ^2.0.0
  firebase_core: ^4.1.0
  firebase_storage: ^13.0.1
  firebase_auth: ^6.0.2
  file_picker: ^10.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 800
        - asset: assets/fonts/Lato-Light.ttf
          weight: 200
        - asset: assets/fonts/Lato-Italic.ttf
        - asset: assets/fonts/Lato-BoldItalic.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/play_store_512.png"
  adaptive_icon_foreground: "assets/play_store_512.png"
  adaptive_icon_background: "#57859D"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/1024.png"
    background_color: "#57859D"

flutter_native_splash:
  color: "#57859D"
  image: "assets/justMonik.png"
  android: true
  ios: true
  web: true

flutter_intl:
  enabled: true
